### PR TITLE
simpler status for draft period

### PR DESCRIPTION
**Pull request by koalie**
Per feedback from @tidoust and @svgeesus

### CODE REVIEW

**Comment by koalie** [comment]
This is a result of https://github.com/w3c/charter-drafts/pull/199#discussion_r291711161

**Review by svgeesus — APPROVED** [review]
Great!

**Comment by svgeesus** [comment]
So ...  is this going to be merged? (I can't)

**Comment by koalie** [comment]
Et voilà !
Thanks for the nudge, @svgeesus 
I had completely forgotten about this.

**Pull request merged**
